name: terraform

on:
  pull_request:
    paths: ["terraform/**"]
  push:
    branches: [main]
    paths: ["terraform/**"]

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    runs-on: ubuntu-latest
    concurrency:
      group: tf-plan-${{ github.ref }}
      cancel-in-progress: true
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5
          terraform_wrapper: false

      - name: Configure AWS (plan role via OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::872515279539:role/gha-terraform-plan
          aws-region: us-east-2

      - name: Who am I (STS)
        run: aws sts get-caller-identity

      - name: Init
        run: terraform init -input=false -reconfigure

      - name: Format & Validate
        run: |
          terraform fmt -check
          terraform validate

      - name: Select/Create dev workspace
        run: terraform workspace select -or-create=true dev

      - name: Plan (dev)
        run: terraform plan -input=false -var-file=environments/dev.tfvars -out=tfplan-dev

      - name: Upload dev plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-dev
          path: terraform/tfplan-dev

      - name: Select/Create prod workspace
        run: terraform workspace select -or-create=true prod

      - name: Plan (prod)
        run: terraform plan -input=false -var-file=environments/prod.tfvars -out=tfplan-prod

      - name: Upload prod plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-prod
          path: terraform/tfplan-prod

  apply-prod:
    if: github.ref == 'refs/heads/main'
    needs: plan
    runs-on: ubuntu-latest
    timeout-minutes: 60
    environment: production   
    concurrency:
      group: tf-apply-prod
      cancel-in-progress: false
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5
          terraform_wrapper: false

      - name: Configure AWS (apply role via OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::872515279539:role/gha-terraform-apply
          aws-region: us-east-2

      - name: Who am I (STS)
        run: aws sts get-caller-identity

      - name: Init
        run: terraform init -input=false -reconfigure

      - name: Select/Create prod workspace
        run: terraform workspace select -or-create=true prod

      - name: Download prod plan artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan-prod
          path: terraform

      - name: Apply (prod) — requires manual approval on this job
        run: terraform apply -input=false -auto-approve tfplan-prod
