name: terraform

on:
  pull_request:
    paths: ["terraform/**"]
  push:
    branches: [main]
    paths: ["terraform/**"]

permissions:
  id-token: write     
  contents: read

jobs:
  plan:
    runs-on: ubuntu-latest
    concurrency:
      group: tf-plan
      cancel-in-progress: true
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Configure AWS (plan role via OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::872515279539:role/gha-terraform-plan
          aws-region: us-east-2

      - name: Who am I (STS)
        run: aws sts get-caller-identity

      - name: Init
        run: terraform init -reconfigure

      - name: Format & Validate
        run: |
          terraform fmt -check
          terraform validate

      - name: Plan (dev)
        run: |
          terraform workspace select dev || terraform workspace new dev
          terraform plan -input=false -var-file=environments/dev.tfvars -out=dev.plan
      - name: Upload dev plan
        uses: actions/upload-artifact@v4
        with:
          name: dev-plan
          path: terraform/dev.plan

      - name: Plan (prod)
        run: |
          terraform workspace select prod || terraform workspace new prod
          terraform plan -input=false -var-file=environments/prod.tfvars -out=prod.plan
      - name: Upload prod plan
        uses: actions/upload-artifact@v4
        with:
          name: prod-plan
          path: terraform/prod.plan

  apply-dev:
    if: github.ref == 'refs/heads/main'
    needs: plan
    runs-on: ubuntu-latest
    timeout-minutes: 60
    concurrency:
      group: tf-apply-dev
      cancel-in-progress: false
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Configure AWS (apply role via OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::872515279539:role/gha-terraform-apply
          aws-region: us-east-2

      - name: Who am I (STS)
        run: aws sts get-caller-identity

      - name: Init
        run: terraform init -reconfigure

      - name: Apply (dev)
        run: |
          terraform workspace select dev || terraform workspace new dev
          terraform apply -input=false -auto-approve -var-file=environments/dev.tfvars

  apply-prod:
    if: github.ref == 'refs/heads/main'
    needs: apply-dev
    runs-on: ubuntu-latest
    timeout-minutes: 60     # runtime after approval
    environment: prod       # requires approval in repo Settings → Environments
    concurrency:
      group: tf-apply-prod
      cancel-in-progress: false
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Configure AWS (apply role via OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::872515279539:role/gha-terraform-apply
          aws-region: us-east-2

      - name: Who am I (STS)
        run: aws sts get-caller-identity

      - name: Init
        run: terraform init -reconfigure

      - name: Apply (prod)
        run: |
          terraform workspace select prod || terraform workspace new prod
          terraform apply -input=false -auto-approve -var-file=environments/prod.tfvars
